G4INSTALL=..

name := G4hadronic_bert_cascade

ifdef G4CASCADE_COULOMB_DEV
  CPPFLAGS += -DG4CASCADE_COULOMB_DEV=1
endif

ifdef G4CASCADE_DEBUG_CHARGE
  CPPFLAGS += -DG4CASCADE_DEBUG_CHARGE=1
endif

ifdef G4CASCADE_DEBUG_INTERFACE
  CPPFLAGS += -DG4CASCADE_DEBUG_INTERFACE=1
endif

ifdef G4CASCADE_DEBUG_SAMPLER
  CPPFLAGS += -DG4CASCADE_DEBUG_SAMPLER=1
endif

ifdef G4CASCADE_DEBUG_SORT
  CPPFLAGS += -DG4CASCADE_DEBUG_SORT=1
endif

ifdef G4CASCADE_WATCHER_HIGHZ
  CPPFLAGS += -DG4CASCADE_WATCHER_HIGHZ=1
endif

ifdef G4CASCADE_SKIP_ECONS
  CPPFLAGS += -DG4CASCADE_SKIP_ECONS=1
endif

ifdef G4CASCADE_DO_COALESCENCE
  CPPFLAGS += -DG4CASCADE_DO_COALESCENCE=1
endif

include $(G4INSTALL)/config/architecture.gmk

CPPFLAGS += -DG4HADRONIC_ALLOC_EXPORT
CPPFLAGS += -I$(G4INSTALL)/external 

include $(G4INSTALL)/config/common.gmk

